version: "3.8"

services:
  rabbitmq:
    image: 'rabbitmq:3.13.0-management'
    container_name: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mongo:
    image: 'mongo:7.0.6'
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - ./.temp/mongo/db:/data/db
  mysql:
    image: 'mysql:8.3'
    container_name: 'mysql'
    ports:
      - '3306:3306'
    volumes:
      - ./.temp/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
