version: "3.8"

services:
  rabbitmq:
    image: 'rabbitmq:3.13.0-management'
    container_name: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mongo:
    image: 'mongo:7.0.6'
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - './.temp/mongo/db:/data/db'
  mongo-express:
    image: 'mongo-express:1.0.2-20'
    container_name: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=root:root@mongodb
